### install packages

In [ ]:
pip install pandas numpy matplotlib polars pyarrow plotly nbformat kaleido

In [1]:
import pandas as pd
import numpy as np
import polars as pl
import gc
import pyarrow
from pathlib import Path #to keep importing datasets from relative paths consistent across OS
import plotly
import plotly.express as px
import nbformat
import plotly.io as pio
import kaleido

### define path

In [2]:
#Get current notebook directory
current_dir = Path(__file__).parent if "__file__" in globals() else Path.cwd()

# Define path relative to project root
data_path = current_dir.parent.parent / "data"

## read data

In [ ]:
df = pl.read_csv(data_path / 'random_state158.csv')

### data cleaning

In [4]:
# userId_y and timestamp_y come from tags and should be dropped
# correct userId_x and timestamp_x names
df = df.drop(["userId_y","timestamp_y"])

In [5]:
df = df.rename({
    'userId_x' : 'userId',
    'timestamp_x' : 'timestamp'
})

In [6]:
df.head()

shape: (5, 9)
┌────────┬─────────┬────────┬────────────┬───┬───────────────┬────────────────┬────────┬────────┐
│ userId ┆ movieId ┆ rating ┆ timestamp  ┆ … ┆ title         ┆ genres         ┆ imdbId ┆ tmdbId │
│ ---    ┆ ---     ┆ ---    ┆ ---        ┆   ┆ ---           ┆ ---            ┆ ---    ┆ ---    │
│ i64    ┆ i64     ┆ f64    ┆ i64        ┆   ┆ str           ┆ str            ┆ i64    ┆ f64    │
╞════════╪═════════╪════════╪════════════╪═══╪═══════════════╪════════════════╪════════╪════════╡
│ 17682  ┆ 31433   ┆ 3.5    ┆ 1544094795 ┆ … ┆ Wedding Date, ┆ Comedy|Romance ┆ 372532 ┆ 6961.0 │
│        ┆         ┆        ┆            ┆   ┆ The (2005)    ┆                ┆        ┆        │
│ 17682  ┆ 31433   ┆ 3.5    ┆ 1544094795 ┆ … ┆ Wedding Date, ┆ Comedy|Romance ┆ 372532 ┆ 6961.0 │
│        ┆         ┆        ┆            ┆   ┆ The (2005)    ┆                ┆        ┆        │
│ 17682  ┆ 31433   ┆ 3.5    ┆ 1544094795 ┆ … ┆ Wedding Date, ┆ Comedy|Romance ┆ 372532 ┆ 6961.0 │
│        ┆         ┆        ┆            ┆   ┆ The (2005)    ┆                ┆        ┆        │
│ 17682  ┆ 31433   ┆ 3.5    ┆ 1544094795 ┆ … ┆ Wedding Date, ┆ Comedy|Romance ┆ 372532 ┆ 6961.0 │
│        ┆         ┆        ┆            ┆   ┆ The (2005)    ┆                ┆        ┆        │
│ 17682  ┆ 31433   ┆ 3.5    ┆ 1544094795 ┆ … ┆ Wedding Date, ┆ Comedy|Romance ┆ 372532 ┆ 6961.0 │
│        ┆         ┆        ┆            ┆   ┆ The (2005)    ┆                ┆        ┆        │
└────────┴─────────┴────────┴────────────┴───┴───────────────┴────────────────┴────────┴────────┘

In [7]:
df.shape

(103531029, 9)

### statistics: totals

In [8]:

# Count unique userId and movieId
unique_userId = df["userId"].n_unique()
unique_movieId = df["movieId"].n_unique()

print(unique_userId, unique_movieId)

75598 12301

## Remove "tag" column for fast summaries

In [9]:
# 1. Drop the 'tag' column if it exists
if "tag" in df.columns:
    df = df.drop("tag")

# 2. Remove duplicate rows
df = df.unique()

In [10]:
gc.collect()
df.shape

(149177, 8)

### convert to pandas df

In [11]:
df = df.to_pandas()

In [14]:
# write to csv for future use
df.to_csv(data_path / 'sample_no_tags.csv')

In [3]:
### read no tags csv sample if needed
df = pd.read_csv(data_path / "sample_no_tags.csv")

### statistics

In [ ]:
# show plots in browser
pio.renderers.default = "browser"  # change to notebook if you want in line in notebook

In [ ]:

#4a. Distribution of unique userId per movieId
user_per_movie = df.groupby('movieId')['userId'].nunique().reset_index(name='unique_user_count')
fig1 = px.histogram(user_per_movie, x='unique_user_count', nbins=50, title='Unique userId per movieId')
fig1.show()

In [6]:

# 4b. Distribution of unique movieId per userId
movie_per_user = df.groupby('userId')['movieId'].nunique().reset_index(name='unique_movie_count')
fig2 = px.histogram(movie_per_user, x='unique_movie_count', nbins=50, title='Unique movieId per userId')
fig2.show()

In [8]:

# Calculate each user's average rating
user_avg_rating = df.groupby("userId")["rating"].mean().reset_index(name="avg_rating")

# Plot the distribution
fig = px.histogram(user_avg_rating, x="avg_rating", nbins=10,
                   title="Distribution of Each User's Average Ratings")
fig.show()

### convert timestamp to datetime

In [9]:
df['datetime'] = pd.to_datetime(df['timestamp'], unit='s')

In [10]:
df.head()

,Unnamed: 0,userId,movieId,rating,timestamp,title,genres,imdbId,tmdbId,datetime
0,0,150853,202439,5.0,1673217328,Parasite (2019),Comedy|Drama,6751668,496243.0,2023-01-08 22:35:28
1,1,29806,58559,5.0,1458854624,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX,468569,155.0,2016-03-24 21:23:44
2,2,180698,44709,3.5,1448160034,Akeelah and the Bee (2006),Drama,437800,13751.0,2015-11-22 02:40:34
3,3,27633,3623,3.5,1681604564,Mission: Impossible II (2000),Action|Adventure|Thriller,120755,955.0,2023-04-16 00:22:44
4,4,86339,1590,4.0,945442048,Event Horizon (1997),Horror|Sci-Fi|Thriller,119081,8413.0,1999-12-17 14:47:28

In [15]:

#Group by time (e.g., monthly) and count ratings
user_activity = df.groupby(pd.Grouper(key='datetime', freq='M'))['userId'].count().reset_index(name='rating_count')

# Plot the distribution
fig = px.line(user_activity, x='datetime', y='rating_count',
              title='User Rating Activity Over Time',
              labels={'rating_count': 'Number of Ratings per Month'})
fig.show()

/var/folders/xj/r1x3kdf11q5bkkj160cjq1pw0000gn/T/ipykernel_85840/2898496257.py:2: FutureWarning:

'M' is deprecated and will be removed in a future version, please use 'ME' instead.

In [14]:

# Compute average rating per movie
movie_avg = df.groupby("movieId")["rating"].mean().reset_index(name="avg_rating")

# Plot histogram of average ratings
fig = px.histogram(movie_avg, x="avg_rating", nbins=10,
                   title="Distribution of Average Ratings per Movie")
fig.show()